<thead>
    <tr>
        <td>Talle </td>
        <td>.cm</td>
    </tr>
</thead>
<tbody>
    <tr>
        <td>35</td>
        <td>22.8cm</td>
    </tr>
    <tr>
        <td>36</td>
        <td>23.5cm</td>
    </tr>
    <tr>
        <td>37</td>
        <td>24.1cm</td>
    </tr>
    <tr>
        <td>38</td>
        <td>25cm</td>
    </tr>
    <tr>
        <td>39</td>
        <td>25.5cm</td>
    </tr>
    <tr>
        <td>40</td>
        <td>26cm</td>
    </tr>
    <tr>
        <td>41</td>
        <td>26.5cm</td>
    </tr>
</tbody>